# Generated by Django 3.0.4 on 2020-03-23 02:58

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates that the record is active. Instead of deleting the record, uncheck this.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='last update')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Description')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('address', jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='Address')),
                ('open_at', models.TimeField(verbose_name='Open at')),
                ('close_at', models.TimeField(verbose_name='Close at')),
                ('days_of_weak', multiselectfield.db.fields.MultiSelectField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], max_length=56, verbose_name='Days of weak')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
            },
        ),
        migrations.CreateModel(
            name='FoodRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates that the record is active. Instead of deleting the record, uncheck this.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='last update')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=250, verbose_name='Description')),
                ('category', models.CharField(choices=[('OTHERS', 'Others'), ('BRAZILIAN', 'Brazilian'), ('ARABIC', 'Arabic'), ('ASIAN', 'Asian'), ('MEXICAN', 'Mexican'), ('ITALIAN', 'Italian'), ('SCNACK', 'Snack'), ('PACKED_LUNCH', 'Packed lunch'), ('MEAT', 'Meat'), ('PIZZA', 'Pizza'), ('PASTA', 'Pasta'), ('FIT', 'Fit'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('DRINK', 'Drink')], default='OTHERS', max_length=50, verbose_name='Category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price')),
                ('preparation_time', models.TimeField(verbose_name='Preparation time')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_recipes', to='kitchen.Chef')),
            ],
            options={
                'verbose_name': 'Food Recipe',
                'verbose_name_plural': 'Food Recipes',
            },
        ),
    ]
